version: "3.2"
services:
  backend:
    image: tla-backend
    container_name: tla-backend

    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env

    ports:
      - 8080:8080

    networks:
      - postgres_network

  postgres:
    image: postgres:15.1-alpine
    container_name: postgres

    env_file:
      - .env

    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - 5432:5432

    networks:
      - postgres_network

  pgadmin:
    image: dpage/pgadmin4:6.15
    container_name: pgadmin4

    logging:
      driver: none

    env_file:
      - .env

    ports:
      - 5050:80

    networks:
      - postgres_network

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge
