CREATE TABLE
    "todos" (
        "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
        "description" VARCHAR(255) NOT NULL,
        "completed" BOOLEAN NOT NULL DEFAULT false,
        "create_date" INTEGER NOT NULL DEFAULT extract(
            epoch
            from now()
        )
    )